# Setup
title:            GDP Blog
tagline:          'Programming & Study'
description:      'Personal Blog of Giuliano Di Pasquale; Occasional Blog posts about Programming'
url:              https://nooby.github.io
baseurl:          '/'
paginate:         5

# About and contact
author:
  name:           'Giuliano Di Pasquale'
  url:            https://github.com/Nooby

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

